
imagePullSecrets: []

image:
  registry: public.ecr.aws
  repository: aws-secrets-manager/secrets-store-csi-driver-provider-aws
  ## defaults to app.Version
  tag: 
  pullPolicy: IfNotPresent

nodeSelector: {}
tolerations: []

port: 8989

privileged: false

resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    cpu: 50m
    memory: 100Mi

podLabels: {}
podAnnotations: {}

updateStrategy:
  type: RollingUpdate

## Configuration values for the secrets-store-csi-driver dependency.
## ref: https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/master/charts/secrets-store-csi-driver/README.md
##
secrets-store-csi-driver:
  install: true
  syncSecret:
    enabled: false

## Install default service account
rbac:
  install: true
  pspEnabled: false
  serviceAccount:
    name:
    roleArn: ""

priorityClassName: ""
