{{ if .Values.rbac.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sscdpa.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{ include "sscdpa.labels" . | indent 2 }}
{{- if .Values.rbac.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.rbac.serviceAccount.roleArn | quote }}
{{- end }}
{{ end }}
